### ISSUE TITLE
Can you add please paper

### ISSUE THREAD

**Issue by buzaev-fedor** [bitzhangcy/Neural-PDE-Solver#2]
Hello, dear @bitzhangcy!

Can you add please my scientific paper 

https://link.springer.com/article/10.1007/s10994-023-06442-6

Have a nice day!

**Comment by DK-fish** [comment]
收到，感谢你（们）的祝福！

**Comment by bitzhangcy** [comment]
Your scientific paper has been added. Have a great day!
